package config

const (
	EnvPrefix string = "AVALOND"

	EnvEnvironment      string = "ENVIRONMENT"
	EnvLogLevel         string = "LOG_LEVEL"
	EnvLogKind          string = "LOG_KIND"
	EnvGatewayHost      string = "GATEWAY_HOST"
	EnvGatewayPort      string = "GATEWAY_PORT"
	EnvNatsAddress      string = "NATS_ADDRESS"
	EnvNatsEncoding     string = "NATS_ENCODING"
	EnvOidcProvider     string = "OIDC_PROVIDER"
	EnvOidcClientId     string = "OIDC_CLIENT_ID"
	EnvDatabaseKind     string = "DB_KIND"
	EnvDatabaseHost     string = "DB_HOST"
	EnvDatabaseUsername string = "DB_USERNAME"
	EnvDatabasePassword string = "DB_PASSWORD"
	EnvDatabaseName     string = "DB_DATABASE"
	EnvBlueprintVersion string = "BLUEPRINT_VERSION"

	FlagEnvironment      string = "environment"
	FlagLogLevel         string = "log-level"
	FlagLogKind          string = "log-kind"
	FlagGatewayHost      string = "host"
	FlagGatewayPort      string = "port"
	FlagNatsAddress      string = "nats-address"
	FlagNatsEncoding     string = "nats-encoding"
	FlagOidcProvider     string = "oidc-provider"
	FlagOidcClientId     string = "oidc-client-id"
	FlagDatabaseKind     string = "db-kind"
	FlagDatabaseHost     string = "db-host"
	FlagDatabaseUsername string = "db-username"
	FlagDatabasePassword string = "db-password"
	FlagDatabaseName     string = "db-name"
	FlagBlueprintVersion string = "blueprint-version"
)
